### ISSUE TITLE
Need to remove windows-10-byol from docs

### ISSUE THREAD

**Issue by WestonThayer** [GoogleCloudPlatform/compute-image-tools#1036]
https://github.com/GoogleCloudPlatform/compute-image-tools/releases/tag/v20191206 removed the `windows-10-byol` os type, and added `windows-10-x64-byol` and `windows-10-x86-byol`. But the [docs](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/205044c6bc06aa896d7eb6117e41aa931430becd/cli_tools/gce_vm_image_import/README.md#required-flags) haven't been updated.

Likewise, `gcloud compute images import` needs to be updated.

**Comment by WestonThayer** [comment]
Since `gcloud compute images import` won't accept `--os windows-10-x64-byol`, you can work around it for now by creating a cloudbuilld YAML file:

```yaml
steps:
  - name: gcr.io/compute-image-tools/gce_vm_image_import:release
    args:
      [
        "-source_file=...",
        "-os=windows-10-x64-byol",
      ]
```

Then `gcloud builds submit --config=above.yaml --no-source`.

**Comment by rofuentes** [comment]
gcloud SDK will have the new os types in the 273.0.0 release scheduled for 2019-12-10. Documentation PR is forthcoming.
