### ISSUE TITLE
Shared VPC model not supported.

### ISSUE THREAD

**Issue by BenCoughlan15** [GoogleCloudPlatform/compute-image-tools#1040]
Hi there,

I have a prod account, where I want my instance to be, but the networking is on a shared VPC.

so if I run the following :

`gcloud --project Ben-Prod-Account compute instances import image-prod --source-uri=gs://Ben-Prod-Bucket/clone-12345-12345-0000.ova --os windows-2012r2 --network projects/Ben-Shared-VPC-Account/regions/europe-west2/networks/ben-net01 --subnet projects/Ben-Shared-VPC-Account/regions/europe-west2/subnetworks/Ben-api-misc --zone europe-west2-c`

it gives me the error:

> [import-ovf]: 2019-12-10T11:41:41Z Error validating workflow: step create-data-disk-import-instance-1 validation error: missing reference for subnetwork **regions/europe-west2/subnetworks/**projects/Ben-Shared-VPC-Account/regions/europe-west2/subnetworks/Ben-api-misc
> [import-ovf] 2019-12-10T11:41:41Z step "create-data-disk-import-instance-1 validation error: missing reference for **subnetwork regions/europe-west2/subnetworks/**projects/Ben-Shared-VPC-Account/regions/europe-west2/subnetworks/Ben-api-misc
> 

The network/subnetwork flags are automatically pre-appending **regions/europe-west2/subnetworks/** to the command line.

This breaks the model that Google Architects recommend, which is to use a shared VPC for networking.

Can we get a way of using a fully qualified network, i.e. with another flag perhaps?

Cheers,
Ben

**Comment by dntczdx** [comment]
Working on it: PR 1043

**Comment by ericbouchard** [comment]
I get this error, and the <number> seems to be different everytime, not sure how to resolve this.

The service account of this project does not have the required permissions to use Shared VPC from host project <project-name>. Please add <number>@cloudservices.gserviceaccount.com as a compute.networkUser role member on project <vpc-host project name>.

**Comment by zoran15** [comment]
Eric, can you open another github issue to describe difficulties you're experiencing with import?

Regarding shared VPCs, you're correct Cloud Build service account in the project where import is performed has to have compute.networkUser role on the project where shared VPC is hosted. This is something you as a user have to do right now and is documented in our image import docs (related to instance import for which we still need to update docs): https://cloud.google.com/compute/docs/import/importing-virtual-disks#shared-vpc

**Comment by zoran15** [comment]
https://cloud.google.com/compute/docs/import/importing-virtual-disks#shared-vpc
