### ISSUE TITLE
Error importing CentOs7

### ISSUE THREAD

**Issue by Aron2560** [GoogleCloudPlatform/compute-image-tools#1139]
I've tried many times importing a (custom) centos7 VHD image. Getting the following error;

`Error running workflow: step "translate" run error: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal FailureMatch found for "inst-translator-import-and-translate-translate-translate-wr0wy": "TranslateFailed: error: command: No '/dev/log' or 'logger' included for syslog logging"`

I know for a fact that the directory dev/log exists with normal regular permissions.

What could be the solution?
Full logs attached.
Thanks much.
[log-c10b443d-f330-4aab-84fe-bb7e6364fc41.txt](https://github.com/GoogleCloudPlatform/compute-image-tools/files/4217796/log-c10b443d-f330-4aab-84fe-bb7e6364fc41.txt)

**Comment by EricEdens** [comment]
Hi, and thanks for the report!

The message `No '/dev/log' or 'logger'` is a warning that occurs when a logging implementation is not found. So, a red herring in this case. I created #1143 to fix that.

Can you go back to your original centos7 machine, run `depmod` for each of the kernels, create another VHD, and import that? For `depmod`, something like this should work:

`for i in /lib/modules/*; do depmod $(basename $i); done`

**Comment by Aron2560** [comment]
Wow. It worked. I can't believe that a single line command was in my way for four weeks now.
The image imported successfully and the the VM is now up and running.
Thank you so much.

Attached is the logs from successful import, In case there is any valuable information for comparison.
[log-330213ec-51fb-48c6-b814-13bb0787d3af.txt](https://github.com/GoogleCloudPlatform/compute-image-tools/files/4229089/log-330213ec-51fb-48c6-b814-13bb0787d3af.txt)

**Comment by EricEdens** [comment]
Great to hear! Thanks again for opening the issue :)
