### ISSUE TITLE
EL: Always call depmod

### ISSUE THREAD

**Issue by EricEdens** [GoogleCloudPlatform/compute-image-tools#1144]
Right now we [call depmod](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/image_import/enterprise_linux/translate.py#L158-L160) for EL 8. Based on #1139, we should call it for EL 7, and perhaps for EL 6 as well.

**Comment by kkm000** [comment]
@EricEdens, here's a permalink, before it runs away (the one in ticket is already off by 10 or so lines):
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/746981f1855c2e45bc7e1c38f4e7932fe7e3f2d7/daisy_workflows/image_import/enterprise_linux/translate.py#L166-L168
