### ISSUE TITLE
A race between two serial logging pumps

### ISSUE THREAD

**Issue by kkm000** [GoogleCloudPlatform/compute-image-tools#1160]
Sorry if this has been logged, but I could not find a similar issue, and it has bothered be for a while.

This is a loop pumping serial port log to the log bucket. This is always on, and all fine (except it loses the tail of the log if the machine shuts town too quickly, but that's a GCE design defect, a whole another story--ideally, GCE should have kept the log open for another 15-30 second after the instance stops). I do not remember off the top of my head where exactly, but I seen in some of the workflows in this repo that a machine is even restarted with the only goal to extract its logs. I am talking about this loop:

https://github.com/GoogleCloudPlatform/compute-image-tools/blob/c776c023bd4e2908d5194634e7740f66119ec011/daisy/logger.go#L261-L268

The real race inside Daisy happens between this pump, and the one in `WaitForInstancesSignal` (WFIS). The latter may react so quickly and issue the .stop to instance that a solid trailing chunk of logs disappears, because the first pump nods it off. And you'd probably be much less than surprised that I'm going after these logs only when build fails, and the tail, the part that was probably the most crucial for diagnostics, would be missing. I'm talking about this loop:

https://github.com/GoogleCloudPlatform/compute-image-tools/blob/c776c023bd4e2908d5194634e7740f66119ec011/daisy/step_wait_for_instances_signal.go#L122-L175

I understand is not an easy problem to solve, and I have a solid chunk of boilerplate in every build script to work around these issues with a various degree of success: Two sleeps, essentially: one before logging the magic incantations for the WFIS step to match, and another after it but before a poweroff to give Daisy a break to suck out the remainder of the log--there is a surge of logging noise when the instance is stopping. Getting the timeout right to avoid false negatives is closer to magic than engineering, tho :)

 If it was only somehow possible to keep a single pump, so that what would have gone to the the bucket and/or stackdriver were exactly the same chunk of log that WFIS had seen and acted upon, that would have solved a half of the issue already. In other words, If WFIS were to somehow tap into the existing log stream pumping service inside Daisy instead of rolling the second one on its own. Do you think something like this is doable?

**Comment by EricEdens** [comment]
Thanks for the thorough analysis! We're pricked by this thorn as well, and while we've talked about solutions, we haven't implemented any yet. I'll start those conversations again, though, and keep this issue updated.

**Comment by kkm000** [comment]
@EricEdens, it just suddenly occurred to me. Last year GCE introduced Guest attributes, and I now use them to report initial status of a deployment (I am running compute clusters, and my single image specialize machines on the first boot as one of 4 types of nodes: login, controller, NFS server; and a preemptible compute node). The deployment script waits for a signal from the first three, permanent type of nodes, indicating they successfully figured out and assumed the required sub-identity each. Maybe this can be a solution independent of log polling?

No question about the existing, log matching a magic word mechanism--existing workflow should be supported--but as the "legacy" vs "recommended" new type of signaling they may be useful, I believe.

**Comment by kkm000** [comment]
BTW, I am not really a Go programmer--I wrote two only production pieces in Go of code in my life, one a self-hosted Web server back in my Google days for the team to gather all the interesting ad stats in a single page from multiple backends, and another that pulled and decrypted the machine SSH keys from KMS so that all cluster machines have the same identity key (dropped it since in favor of the new Secrets API, much easier to use and audit). But you can use me to document the new feature, if you decide to use the Guest attrs (it would involve a curl incantation to signal success/failure). Please @-mention me if you think I can be of help. These go to my inbox and also even bleep on the phone.

**Comment by EricEdens** [comment]
Hi @kkm000. The [guest attributes](https://cloud.google.com/compute/docs/storing-retrieving-metadata#guest_attributes) idea is interesting, but would still require coordination with the logging mechanism to ensure that all serial logs have been archived prior to terminating the worker instance. So, I'd recommend filing a feature request for guest attributes, since I think they're orthogonal to the problem in this issue. (Unless I'm missing something!)

To distil this current issue, these steps need to be serialized:

1. Fetch the latest serial console logs
2. Archive them
3. Process rules in `WaitForInstancesSignal`

I'm still exploring different options to achieve this. It sounds like you have a mitigation on your end, is that right?
