### ISSUE TITLE
Issue in Importing OVA/OVF

### ISSUE THREAD

**Issue by RahulSinghKumar** [GoogleCloudPlatform/compute-image-tools#1229]
Hello All,

When I am trying to import OVA or OVF, I am getting below stated error.
PFA for the all logs.
Need your help in this regards,

Thank you
[OVA.txt](https://github.com/GoogleCloudPlatform/compute-image-tools/files/4698219/OVA.txt)

found: "TranslateStatus: Function <function install_apt_packages at 0x7f2a03ccf1e0> failed, waiting 129 seconds, retrying 13 ..."
[import-ovf]: 2020-05-28T20:16:45Z Error running workflow: step "translate" run error: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal FailureMatch found for "inst-translator-import-ovf-translate-translate-disk-j1vd8": "TranslateFailed: error: sh: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution)."

**Comment by EricEdens** [comment]
Hi @RahulSinghKumar

The error occured when apt-get was trying to install cloud-init, and apt-get is suggestion that you run `--fix-broken`[1]. You'd do that on the original machine from which the OVA was produced.

While you're there, I'd also recommend the following three commands. This will ensure that your system is updated, and that you are able to observe that cloud-init can be installed. If you don't want to install cloud-init on the original machine, you could run the installation using `--dry-run`.

* apt-get update
* apt-get upgrade (or dist-upgrade if you prefer)
* apt-get install cloud-init

One finished, re-export a new OVA.

Hope this helps!

___

1. http://manpages.ubuntu.com/manpages/xenial/en/man8/apt-get.8.html

**Comment by Narennnn** [comment]
Hello Guys,

Receiving  this error. Unable to fix it. I am using a OVA file of linux Vm and importing it in GCP. 
Could you please help. Below is the error file. 

[translate]: 2022-11-15T15:16:05Z Uploading sources
[translate]: 2022-11-15T15:16:09Z Running workflow
[translate]: 2022-11-15T15:16:09Z Running step "translate-disk" (IncludeWorkflow)
[translate.translate-disk]: 2022-11-15T15:16:09Z Running step "setup-disk" (CreateDisks)
[translate.translate-disk.setup-disk]: 2022-11-15T15:16:09Z CreateDisks: Creating disk "disk-translator-translate-translate-disk-112v6".
[translate.translate-disk]: 2022-11-15T15:16:12Z Step "setup-disk" (CreateDisks) successfully finished.
[translate.translate-disk]: 2022-11-15T15:16:12Z Running step "translate-disk-inst" (CreateInstances)
[translate.translate-disk.translate-disk-inst]: 2022-11-15T15:16:12Z CreateInstances: Creating instance "inst-translator-translate-translate-disk-112v6".
[translate.translate-disk]: 2022-11-15T15:16:22Z Step "translate-disk-inst" (CreateInstances) successfully finished.
[translate.translate-disk]: 2022-11-15T15:16:22Z Running step "wait-for-translator" (WaitForInstancesSignal)
[translate.translate-disk.translate-disk-inst]: 2022-11-15T15:16:22Z CreateInstances: Streaming instance "inst-translator-translate-translate-disk-112v6" serial port 1 output to https://storage.cloud.google.com/fabled-badge-368111-ovf-import-bkt-asia-northeast2/n46gz/boot-image-my-sslingshot/daisy-translate-20221115-15:16:03-112v6/logs/inst-translator-translate-translate-disk-112v6-serial-port1.log
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:16:22Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": watching serial port 1, SuccessMatch: "TranslateSuccess:", FailureMatch: ["TranslateFailed:" "Failed to download GCS path"] (this is not an error), StatusMatch: "TranslateStatus:".
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:16:34Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus: Executing command: ['lsblk', '--noheadings', '--output=NAME', '--paths', '--list', '--nodeps', '-e7']"
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:16:34Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus: /dev/sda"
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:22:03Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus:"
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:22:03Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus: Function <function update_apt at 0x7f9b148b1b70> failed, waiting 1 seconds, retrying 1 ..."
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:24:12Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus:"
[translate.translate-disk.wait-for-translator]: 2022-11-15T15:24:12Z WaitForInstancesSignal: Instance "inst-translator-translate-translate-disk-112v6": StatusMatch found: "TranslateStatus: Function <function update_apt at 0x7f9b148b1b70> failed, waiting 1 seconds, retrying 2 ..."
[translate]: 2022-11-15T15:24:12Z Error running workflow: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal FailureMatch found for "inst-translator-translate-translate-disk-112v6": "TranslateFailed: error:"
