### ISSUE TITLE
Files translate_centos.wf.json and translate_rhel.wf.json doesn't exist

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#128]
Files translate_centos.wf.json and translate_rhel.wf.json are used, but they don't exist.

These files are included by:
/daisy/enterprise_linux/translate_centos_7.wf.json
/daisy/enterprise_linux/translate_rhel_7_byol.wf.json
/daisy/enterprise_linux/translate_rhel_7_licensed.wf.json

It generates error messages like the following:
```
koike@daisy-control:~$ daisy -variables source_image=projects/,project./global/images/vmi-centos64-bit /daisy/enterprise_linux/translate_centos_7.wf.json
2017/08/22 11:14:35 error parsing workflow "/daisy/enterprise_linux/translate_centos_7.wf.json": open /daisy/enterprise_linux/translate_centos.wf.json: no such file or directory
```

**Comment by zmarano** [comment]
Fixed by #129
