### ISSUE TITLE
Tensorflow predict generate NaN values on K80

### ISSUE THREAD

**Issue by rafikg** [GoogleCloudPlatform/compute-image-tools#1538]
I am running a code on GCP Debian 10, Cuda 11, and K80 GPU on tensorflow 2.4.1 and 2.4.0. The code is running very well on Colab and on my local machine. However, It generates NaN values on successive predictions. Here is my code on Colab.
[code](https://colab.research.google.com/gist/rafikg/d22b21085e2de8d9ae4503055f03aabe/example.ipynb).
Anyone from the GCP team could check this problem? It is a blocker and I am charging money because of it!

**Comment by zmarano** [comment]
Hi! You may want to redirect this question to the [Tensorflow github project](https://github.com/tensorflow/tensorflow). The compute-image-tools project is for Google Compute Engine image building tools and is not involved in Tensorflow.
