### ISSUE TITLE
Daisy cannot recover from failed GetSerialPortOutput failures.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/compute-image-tools#1557]
It looks like if there's multiple GetSerialPortOutput failures, Daisy will halt the process.
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/dc64ab897d7331b29217d4df6b4cd9cb9d304d1e/daisy/step_wait_for_instances_signal.go#L144

**Comment by EricEdens** [comment]
Hi Jeremy, this is correct. Are you affected by this? If so, thoughts on alternatives?

**Comment by jeremyje** [comment]
Interim fix:

- Use exponential backoff with randomized jitter. It looks like something sorta like that is going on: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/9ae272235f86b6a3dbd657b259ca308126b3288a/daisy/compute/compute.go#L210 but I'm not sure I'd roll my own retry loops there's plenty of golang libraries for this.
- Make the retry logic not fail after 3 times. Make it time bound like say if I keep getting failures for 5 minutes then give up.

Permanent Fix:
Read from 

- Stackdriver logs as the primary source. If there's no access fallback to GetSerialPortOutput with a less aggressive polling internal. Once per minute instead of once every 10 seconds.

**Comment by EricEdens** [comment]
These all sound like reasonable approaches. If you're interested in writing a PR, we could chat about specifics, and I think @adjackura  would have some thoughts too.

Before that, I'm curious: How often do your builds fail due to this?
