### ISSUE TITLE
GCE_Export Release Version access_denied 

### ISSUE THREAD

**Issue by DarrellDM** [GoogleCloudPlatform/compute-image-tools#1845]
Hi Team,

A user have a backup program that utilizes the GCE_Export Go program. They have their backup program pull down the newest version of GCE_Export on every attempt and this has worked for the past few years. They noticed recently that when pulling from the "release" [version](https://storage.googleapis.com/compute-image-tools/release/linux/gce_export), they are getting hit by: 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```
It appears that the bucket/objects is non-public and the user would like access to it.

They are currently using the "latest" [version](https://storage.googleapis.com/compute-image-tools/latest/linux/gce_export) as a workaround, but they would like to go back to using the "release" version. 

Thanks!

**Comment by zoran15** [comment]
When did this behavior start? 

`gce_export` hasn't been worked on much recently so it's less likely it was a code change that is causing this (though not impossible).
