### ISSUE TITLE
Daisy: confusing error when step type misspelled

### ISSUE THREAD

**Issue by ericdand** [GoogleCloudPlatform/compute-image-tools#205]
When the step type of a step is not valid, Daisy reports that no step type is defined:
```
[Daisy] Errors in one or more workflows:
  <workflow-name>: error populating workflow: no step type defined
```
It should instead print out the step type that couldn't be identified (if present) and give an error message like "unrecognized step type: <step-type>".

**Comment by ericdand** [comment]
Code tracing: the first line of the error message is reported in `daisy.go#main()`, specifically around line 197, within `if err:= w.Run(ctx);`. Digging into `workflow.go#Run(ctx)`, it calls `Validate(ctx)`, which contains the string "error populating workflow". `Validate(ctx)` calls `populate(ctx)`, which in turn calls `populateStep(ctx, step)`, which finally calls `step.go#stepImpl()`, the source of the string "no step type defined". So that's where all the parts of this error message come from.

Before the workflow is run, however, it is unmarshalled from a JSON object. This includes unmarshalling all of its steps. This happens in `workflow.go#readWorkflow(file, w)`. Unfortunately, it looks like invalid step types are simply ignored. https://golang.org/pkg/encoding/json/#Unmarshal says:

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. **Unmarshal will only set exported fields of the struct.**

Furthermore:

> If a JSON value is not appropriate for a given target type ... Unmarshal skips that field and completes the unmarshaling as best it can.

So, as it stands, misspelled step types are just dropped silently on the floor.

But there is hope:

> To unmarshal JSON into a value implementing the Unmarshaler interface, Unmarshal calls that value's UnmarshalJSON method, including when the input is a JSON null. Otherwise, if the value implements encoding.TextUnmarshaler and the input is a JSON quoted string, Unmarshal calls that value's UnmarshalText method with the unquoted form of the string.

So, if we add an `UnmarshalJSON` method to our `Workflow` type, then we could do the error checking. I'm yet unsure how much work this would take.

**Comment by ericdand** [comment]
After further consideration, I have two conclusions:

1. It makes more sense to only make `Step` implement the `Unmarshaler` interface, and
2. It does indeed make sense, given the funny way we represent steps (specifically their type) in JSON, to write custom unmarshalling logic for steps.

Happily, to implement `Unmarshaler`, it only takes one method. I'll get right to it.

**Comment by adjackura** [comment]
See this, should be in go 1.10:
https://go-review.googlesource.com/c/go/+/74830

**Comment by ericdand** [comment]
Awesome! Alright, I'll just wait until that's released, then we can use that.

**Comment by crunk1** [comment]
Partial fix out: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/255

Reports the offending step name when there is a step population error.
