### ISSUE TITLE
Need more documentation on "Scopes" when creating instances

### ISSUE THREAD

**Issue by ericdand** [GoogleCloudPlatform/compute-image-tools#213]
I recently needed to give a new instance read-write access to a certain GCS bucket. Our current docs show the "Scopes" field as a thing, but don't really explain how to use it. At bare minimum, we should provide a link [here](https://cloud.google.com/storage/docs/authentication).

**Comment by crunk1** [comment]
Fixed by https://github.com/GoogleCloudPlatform/compute-image-tools/pull/253.
