### ISSUE TITLE
Create custom Windows BYOL images failed

### ISSUE THREAD

**Issue by Pylypp** [GoogleCloudPlatform/compute-image-tools#2233]
Hi
I was trying to build windows 11 image using this [link](https://cloud.google.com/compute/docs/images/creating-custom-windows-byol-images)
1. Error:
```
Error validating workflow: networkResourceDoesNotExist: step "windows-build" validation error: networkResourceDoesNotExist: step "run-bootstrap" validation error: networkResourceDoesNotExist: projects/<PROJECT>/global/networks/default does not exist
```
I couldn't find the way to provide network name so I just created default one. We don't use default networks anywhere
2. Now the build hangs at: 
```
WaitForInstancesSignal: Instance "install-windows-11-21h2-pro-x64-uefi-windows-build-l7x67": watching serial port 1, FailureMatch: ["Windows build failed"] (this is not an error).
```
The instance is shut down already, seeing logs there
```
GCEMetadataScripts: Finished running startup scripts
GCEMetadataScripts: Starting shutdown scripts (version 20230403.00)
GCEMetadataScripts: No shutdown scripts to run
GCEGuestAgent: GCE Agent Stopped
The SAC will become unavailable soon.  The computer is shutting down.
{"@type":"type.googleapis.com/cloud_integrity.IntegrityEvent", "bootCounter":"2", "shutdownEvent":{…}}
compute.googleapis.com compute.instances.guestTerminate …11-21h2-pro-x64-uefi-windows-build-l7x67 system@google.com Instance terminated by guest OS shutdown.
compute.googleapis.com v1.compute.instances.delete …11-21h2-pro-x64-uefi-windows-build-l7x67 ***@cloudbuild.g…
audit_log, method: "v1.compute.instances.delete", principal_email: "***@cloudbuild.gserviceaccount.com"
```
Please help

**Comment by fhacloid** [comment]
Got the same issue here.

**Comment by bkatyl** [comment]
The image build workflows currently only support the default value of the network/subnetwork values.

In the documentation,
https://cloud.google.com/compute/docs/images/creating-custom-windows-byol-images#preparing_the_project, it does include a note of a workaround for making a default network is you don't have a default network.

Note: The build process assumes that your project contains a [default network](https://cloud.google.com/vpc/docs/vpc#default-network). If you've [disabled the creation of default networks](https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints) in your organization, you must manually create an auto-mode VPC network named default.

Another workaround would be to fork the workflows to add those values to the CreateInstances object as the [image-import process](https://github.com/GoogleCloudPlatform/compute-image-import/blob/110224ec011a4a84856ea6081115a9ed61c35da9/daisy_workflows/image_import/inflate_file.wf.json#L92) does that.

Hopefully one of those workaround works for you. I've opened a feature request/enhancement around this specific issue at https://github.com/GoogleCloudPlatform/compute-image-tools/issues/2329
