### ISSUE TITLE
Create new step type(s) to attach and detach disks from instances

### ISSUE THREAD

**Issue by ericdand** [GoogleCloudPlatform/compute-image-tools#247]
We need a new step type with a name like `AttachDisks` to attach disks, and another, call it `DetachDisks` to detach disks. These should attach/detach disks from running instances.

**Comment by gut** [comment]
@adjackura I don't see a `DetachDisks` step type available. On top of that I noticed that I couldn't implement one directly as there is no `compute.DetachedDisks` type (whereas a `compute.AttachedDisk` exists).

Is there currently a way of detaching a disk other than through the cleanup of an instance? Or what would you suggest as an architecture to implement the `DetachDisks` step type?

**Comment by gut** [comment]
Oh, I just noticed the `DetachDisks` from `Instances`. If it works fine, I'll reference this issue on the PR.
