### ISSUE TITLE
Create new step types for networking

### ISSUE THREAD

**Issue by ericdand** [GoogleCloudPlatform/compute-image-tools#248]
We need step types for networking tasks. Ideas so far:

- A `CreateNetworks` step for adding networks
- A step for managing firewall rules
- A step for creating subnetworks

This issue could perhaps be split into multiple issues as work progresses.

**Comment by crunk1** [comment]
PR submitted https://github.com/GoogleCloudPlatform/compute-image-tools/pull/295
