### ISSUE TITLE
Cleanup of instances needs to happen first

### ISSUE THREAD

**Issue by zmarano** [GoogleCloudPlatform/compute-image-tools#292]
Instances need to be deleted before deleting disks. Also, a DeleteResources step to try to delete the instance at the end of the workflow is not working to delete the instance before the rest of the cleanup happens.

https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy/workflow.go#L648

**Comment by crunk1** [comment]
PR out, but this brings up discussion about DeleteResources and one other scenario:

If a CreateInstances call has NoCleanup: true, but the instance(s) use a disk that has NoCleanup: false, assuming that the instance(s) are still around at cleanup time, Daisy will try and fail to delete the disk attached.

**Comment by crunk1** [comment]
@adjackura for discussion

**Comment by crunk1** [comment]
Fixed by #293

**Comment by crunk1** [comment]
Need to write tests to check cleanup. Also, should Daisy return an error code for errors during cleanup?
