### ISSUE TITLE
Documentation TODOs

### ISSUE THREAD

**Issue by crunk1** [GoogleCloudPlatform/compute-image-tools#299]
- CreateDisks/CreateImages/CreateInstances omit ExactName in the resource descriptions.
- CreateImages' description of GuestOsFeatures should be put in the "modifications" table instead of "added fields" table since it is modifying an existing compute.Image field.
- CreateImages' description does not include Overwrite.

**Comment by functicons** [comment]
I wanted to add a TODO: Why Daisy?

This [page](https://googlecloudplatform.github.io/compute-image-tools/daisy.html) explained "What is Daisy?", but I don't quite understand its advantages over a script of gcloud commands.
