### ISSUE TITLE
[question/image_tests]: how an instance add metadata-ssh in another instance

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#315]
Hello,

To implement the metadata ssh linux integration tests I was creating two machines ("tester" and "testee"), the tester machine would generate the ssh keys and update the metadata of the testee machine and verify login.

My current problem is when I run add-metadata from one machine to the other I get an "Insufficient Permission" error. So I suppose I can't alter the ssh-keys without running `gcloud auth login`, is that correct? Is there any other way around?

    + gcloud compute instances add-metadata inst-metadata-ssh-testee-5yg4l --metadata-from-file ssh-keys=tester-ssh-key.pub --zone projects/447259094475/zones/us-central1-b
    ERROR: (gcloud.compute.instances.add-metadata) Could not fetch resource:
     - Insufficient Permission

Here is my current draft implementation: https://github.com/helen-fornazier/compute-image-tools/blob/metadata-ssh/daisy_workflows/image_test/metadata-ssh.wf.json

**Comment by helen-fornazier** [comment]
Another solution is to allow daisy to execute a local script instead of generating the tester machine. What do you think?

**Comment by zmarano** [comment]
You would need to grant the VM that is setting the metadata the right scope to perform actions on instances, in particular it needs "https://www.googleapis.com/auth/compute", [example](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/36cce02f4925f37d659ff4c33b47817bcf9f8cf2/daisy_workflows/image_import/import_image.wf.json#L50)

**Comment by helen-fornazier** [comment]
Great, thanks.
