### ISSUE TITLE
Error validating workflow "workflow": error populating workflow: APIError: dialing: missing 'type' field in credentials

### ISSUE THREAD

**Issue by jsoref** [GoogleCloudPlatform/compute-image-tools#368]
I'm not sure what `dialing` is...

I used https://console.cloud.google.com/apis/credentials to create an `OAuth 2.0 client IDs` and then downloaded the resulting JSON file.

**Comment by adjackura** [comment]
What you need to create is a service account key.  See here for more info: https://cloud.google.com/docs/authentication/production

In short, if no credentials are provided on the command line, Daisy will look in well known locations. If running in GCE it will use the default service account set for the instance. 
Gcloud can also be used to store credentials in a well known location by running 'gcloud auth application-default login', you then do not need to pass the path to the credential file on the command line.

**Comment by jsoref** [comment]
Yeah, I eventually settled on `gcloud auth application-default login` -- It just feels like `dialing` is an odd thing to have as output, there's nothing anywhere that talks about it. -- I can't figure out what it means...

**Comment by adjackura** [comment]
That's just how the error is passed up, the api library has that in the
setup error, probably because it's setting up a tcp connection.

**Comment by jsoref** [comment]
The word `dialing` comes from daisy itself:
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/24859bb2213074212a17c8227db0cde4397090ac/daisy/compute/compute.go#L172

Does it mean `connecting`? Is it trying to tell someone the name of a module under the hood?

**Comment by adjackura** [comment]
Ack, ok I think that was based on previous code. I'll take a look and see
about working out a more clear error message. Thanks
