### ISSUE TITLE
sles11: syslog is not redirected to serial port

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#373]
For image_tests, to wait for some image to boot, I add a startup script to print the message "BOOTED" and I use Daisy WaitForInstancesSignal, but sles11 doesn't seem to send syslog outputs to the serial port and the test fails.

I tested on the latest sles11:
sles-11-sp4-v20180104                                 suse-cloud           sles-11

**Comment by adjackura** [comment]
You can't assume startup script stdout will go to the serial console, it's
better to write to /dev/ttyS0 directly unless your specifically testing
syslog output to the serial console.

I don't think we should rely on syslog writing to the serial console at all
as it makes a lot of assumptions of the host OS (syslog redirection is
setup or that the OS even uses syslog) but that's a separate discussion
entirely.

**Comment by helen-fornazier** [comment]
Right, I see, I'll update the scripts to write to ttyS0 directly then, so I can rely on WaitForInstancesSignal.
Thanks.
