### ISSUE TITLE
[question/image_tests]: method to validate that gcloud/gsutil are up to date

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#400]
As requested on the [configuration tests](https://github.com/GoogleCloudPlatform/compute-image-tools/blame/master/daisy_workflows/image_test/README.md#L163), there should be a "Test for gcloud/gsutil (some distros won’t have this) and validate that versions are up to date." and I thought about 2 different approaches:

1. A specific version for gcloud and gsutil are set on metadata variables and checked on this test. It fails if the specified version is older than the current versions found on the image.

1. The test runs an equivalent `apt-get update && apt-get install --assume-no gcloud` and fails if it returns non-zero (so there is a newer gcloud in the repository).

Which one would you suggest? The former is more robust (cross checks) and the latter more flexible (as it only fails if that distribution repository packed a new version and didn't update the image).

I'm also open to different approaches, if you come up with one.

**Comment by zmarano** [comment]
We would probably want to scope the test to the distros that are expected to have gsutil/gcloud (some won't). But, as far as checking if it up to date- I think that is probably not going to get us very far as it will likely always be out of date (they ship weekly). I think we should instead check if the installed versions work correctly. Probably just do a couple basic things with each to validate that API calls work.

**Comment by gut** [comment]
I see, then could you please suggest some basic "gcloud" commands that would do the trick? If possible, I want to avoid authentication to keep test configurations as simple as possible but I don't know if there would be something meaningful to use without authenticating...
Thanks!

**Comment by zmarano** [comment]
The simplest commands are: `gcloud info` and `gsutil version` so we can start with those.
However, seeing if authentication works (if you give the VM the right scopes, it uses the service account automatically), is a good test to run here as well and see if you can make a simple list API call:
'gcloud compute images list' and 'gsutil ls' should both be able to succeed if the VM has at least read scopes for compute and storage.

**Comment by gut** [comment]
Alright. Thanks for the hints.

As you said that some distributions will not have them, I'm considering the approach of only running this test if gsutil/gcloud are installed. In another words, the test will only fail if the image have them installed but with a version that is not working anymore. By doing that the test wouldn't need a switch mechanism (e.g: Metadata variable) to indicate if such a test needs to run on the system as it's expected to have functional gsutil/gcloud versions.

What do you think? Would it be ok?

**Comment by zmarano** [comment]
That sounds good yes.

**Comment by gut** [comment]
Great, thanks

**Comment by gut** [comment]
quick related question: If gcloud/gsutil are not mandatory on all images, then is the "Ensure apt/yum repos are setup for GCE repos." an optional test as well?

**Comment by gut** [comment]
@zmarano : ping

**Comment by zmarano** [comment]
Oh sorry missed that question. Basically its dependent on distro and where it is built right now.

The breakdown is as follows (currently):
* Debian, CentOS, RHEL will have the SDK installed from the Google Cloud repo and should work.
* Ubuntu versions before 18.04 will have the SDK installed from the Ubuntu repo but it should work correctly.
* Ubuntu 18.04+ will have the SDK available via a snap package but the CLI tools (gcloud/gsutil) shoudl be callable as usual.
* SLES will eventually not have the SDK installed at all so we should not run this test there.
* Container hosts (CoreOS and COS) will not the SDK installed or usable either.
* FreeBSD should have a working SDK but it comes from the FreeBSD port but it should work.

Similarly, checking for Google cloud repos would only apply to Debian, CentOS, and RHEL by default. So in both cases, these tests have case by case options.

**Comment by gut** [comment]
roger. Thanks for the overview.
