### ISSUE TITLE
[question/image_tests/configuration]: what is expected to be verified on kernel command line args

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#402]
Hi once again,

As requested on the [configuration tests](https://github.com/GoogleCloudPlatform/compute-image-tools/blame/master/daisy_workflows/image_test/README.md#L120), there should be a "Ensure boot loader kernel command line args (per distro)." but I need more information. Which arguments do you have in mind?

**Comment by gut** [comment]
@zmarano : can you please help me on this one?

**Comment by zmarano** [comment]
Yeah we may have to break this out more and I am not sure how deep we want to get with validation.
The most important arg that should be the same everywhere is:
console=ttyS0,38400n8

Distros that support multiqueue SCSI should have (Debian 9 and all Ubuntu releases):
scsi_mod.use_blk_mq=Y

Most distros should also have but I don't believe all will so we may ignore that:
elevator=noop

Some distros (Debian is the one I know of) will disable predictive network interface naming which affects networkrules:
net.ifnames=0 biosdevname=0

**Comment by gut** [comment]
And about the other test : "Ensure boot loader configuration for console logging is correct."? At the moment I'm considering having it implicitly tested by the other tests, as many use the console to communicate through "WaitForInstancesSignal"

**Comment by gut** [comment]
or is it simply the "console=ttyS0,38400n8" as you said?
