### ISSUE TITLE
Document what roles a service account created for daisy should have

### ISSUE THREAD

**Issue by paulcdejean** [GoogleCloudPlatform/compute-image-tools#406]
I'm trying to create a service account to use with daisy, but it's not clear what roles said service account should have.

Could best practices for this be documented>

**Comment by zmarano** [comment]
Good point, we should add some better default cases for that.

But, for the most part your service account will need access to modify all compute resources and storage resources, and optionally logging (it can optionally write logs to cloud logging). The simplest way is to give your service account editor access to the project.

If you want to scope permissions further however, you will have to choose [compute](https://cloud.google.com/compute/docs/access/iam#iam_roles) and [storage](https://cloud.google.com/storage/docs/access-control/iam-roles) IAM roles based on what your workflows are doing. For example, if you never have a workflow that modifies network resources, it wouldn't need network admin or security admin per say but would still likely need instance admin and storage read/write.
