### ISSUE TITLE
Prow: pool of projects - design discussion

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#407]
We have some [integration tests for images](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/daisy_workflows/image_test) ready and I would like to move forward to integrate those tests in the [testing infrastructure](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/test-infra).

Several integration tests modifies metadata in the project level, those tests conflicts with each other thus can't be ran in parallel unless we have a way to tell Prow to execute those conflicting tests in different GCE projects.
This prohibits us to have a test per image. The current way to add the integration tests in Prow is to have a single workflow to serialize all the image tests and this is not ideal.

The idea is to have a configuration file where we can define which are the conflicting tests and another to inform Prow a list of GCE projects for it to use. Prow would launch the conflicting tests in parallel, each one in a different project, or serialize the execution if no project is available (if all of them are busy).

I would like to have your feedback on the matter, if this should be in the Prow level or in the workflow description, if you already have any ideas in mind of if I can go on and work on a proposal for the implementation.

**Comment by adjackura** [comment]
I'm still working on the project locking bits (currently not implemented), you can see the tests flaking because of this.
https://k8s-testgrid.appspot.com/google-gce-compute-image-tools#linux-image-tests

**Comment by adjackura** [comment]
This should be fixed with the latest test runner commits. Documentation still TBD as the tool is still in development.
