### ISSUE TITLE
Unknown workflow var "imported_disk" for Windows Server 2016

### ISSUE THREAD

**Issue by gioporta** [GoogleCloudPlatform/compute-image-tools#408]
When attempting to import my Windows Server 2016 disk into Google Cloud, I encounter the following error:
```
[Daisy] Running workflow "import-and-translate" (id=tglms)

[Daisy] Errors in one or more workflows:
  import-and-translate: error populating workflow: error populating step "translate": unknown workflow Var "imported_disk" passed to IncludeWorkflow "translate-image"
ERROR
ERROR: build step 0 "gcr.io/compute-image-tools/daisy:release" failed: exit status 1
```

I did some digging through the workflow configuration files and found that [translate_windows_2016.wf.json](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/d42fe51b8589965f9c0704f67cb52115e48fcd8c/daisy_workflows/image_import/windows/translate_windows_2016.wf.json#L30) has an **imported_disk** var that is passed to [translate_windows_wf.json](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/d42fe51b8589965f9c0704f67cb52115e48fcd8c/daisy_workflows/image_import/windows/translate_windows_wf.json) in the translate-image step. 
```
"Steps": {
    "translate-image": {
      "IncludeWorkflow": {
        "Path": "./translate_windows_wf.json",
        "Vars": {
          "source_disk": "${source_disk}",
          "install_gce_packages": "${install_gce_packages}",
          "sysprep": "${sysprep}",
          "imported_disk": "${disk_name}",
          "drivers": "gs://gce-windows-drivers-public/release/win6.3/",
          "version": "10.0",
          "task_reg": "./task_reg_2016",
          "task_xml": "./task_xml"
        }
},
```

However, [translate_windows_wf.json](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/d42fe51b8589965f9c0704f67cb52115e48fcd8c/daisy_workflows/image_import/windows/translate_windows_wf.json) does not handle this var at all. The [translate_windows_2012_r2.wf.json](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/d42fe51b8589965f9c0704f67cb52115e48fcd8c/daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json) doesn't have this var either and I would assume it works fine.

I believe the solution to this would be to remove the var in question (**imported_disk**) from the workflow config for Windows Server 2016.

**Comment by zmarano** [comment]
Thanks for the bug report, you're right that seems to be an artifact from previous iterations, we will fix it.

**Comment by ericdand** [comment]
Squashed and merged. These changes will be available to `gcloud` soon, once we push out a new release.

**Comment by gioporta** [comment]
When approximately will a new release be pushed? I'm supposed to have the import completed before the 19th. I don't want to rush anything, I just want to know ahead of time so I can plan accordingly.

**Comment by zmarano** [comment]
We are tracking down a different bug before we make a release. I don't expect to have that resolved before Monday. In the mean time, you can try the latest workflow using Daisy directly for this import. The [instructions on this page](https://googlecloudplatform.github.io/compute-image-tools/image-import.html) should work for you and uses the release version of the Daisy binary with the latest workflows committed to this repo so you should not run into the bug we are tracking down.

**Comment by zmarano** [comment]
This is released and should be available via gcloud now.
