### ISSUE TITLE
Fail to set ssh key in metadata

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#414]
When executing [metadata-ssh test](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/daisy_workflows/image_test/metadata-ssh), sometimes it fails to change the metadata values in the instance. The test **thinks** it added an ssh key, then tries to ssh to the instance but it fails because in fact no ssh key was added in the metadata.

# How to reproduce:

## Fail:

Execute:

`daisy -variables source_image=projects/debian-cloud/global/images/family/debian-9 metadata-ssh/metadata-ssh.wf.json`

The tester should have set and ssh key in the instance level of the testee here: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py#L34

But tester fails to ssh to the testee here: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py#L35

If you look at testee instance metadata, there is no ssh key value there.

## Succeed:
But the test succeeds if you duplicate this line https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/image_test/linux_common/utils.py#L319

**Comment by gut** [comment]
Hi. I'm facing those issues also when connecting to recent ubuntu images. Is somebody taking a look at this?
