### ISSUE TITLE
Workflow validation doesn't catch syntax error in 'Name' field in SubWorkflow

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#416]
If a workflow has an invalid name, e.g. `img-test_independent`, executing this workflow fails as expected:

```
[Daisy] Running workflow "img-test_independent" (id=zy2s1)

[Daisy] Errors in one or more workflows:
  img-test_independent: error validating workflow: workflow field 'Name' must start with a letter and only contain letters, numbers, and hyphens
```

But if we use this bad Workflow in a `IncludeWorflow` or `SubWorkflow`, validation doesn't fail.

**Comment by adjackura** [comment]
For IncludeWorkflow and SubWorkflow the name is overwritten with the step name, so the invalid name is never used.

**Comment by adjackura** [comment]
I'm going to close this as the name fields are ignored (along with most top level fields) for subworkflow and include workflows.
