### ISSUE TITLE
[question] Proper way of using local-ssd on daisy

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#426]
I tried to set a "CreateDisks" step with local-ssd and I had no success on doing so. Then I tried to add it directly on "Disks" inside of a "CreateInstances" but I noticed that daisy is not prepared for validating a local-ssd disk type, right?

Are these changes scheduled for being implemented? Or can I start to do this? Is there any architectural suggestion that you'd like to give? For the moment I'm enabling validation of a nameless disk (as the API requests, or else I have a Error 400 "No source can be specified for local SSD.") and clear the URL attributes of the disk. That seems a little bit hacky so I don't know if that's the best way of doing that.

**Comment by adjackura** [comment]
CreateDisks only works with PD disks, so thats expected.
I'll have a validation fix soon for creating local-ssd.

**Comment by gut** [comment]
great! Thanks @adjackura . I'll check that out.
