### ISSUE TITLE
[question/image_tests]: Create networks through daisy

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#436]
As requested on the [Multi NIC tests](https://github.com/GoogleCloudPlatform/compute-image-tools/blame/master/daisy_workflows/image_test/README.md#L188). I would like to know if there is a plan to support network/subnets creation on daisy to implement this test: "Ensure two VM’s with multiple interfaces sharing one VPC network can talk to each other over the VPC." as I guess it would be better to create a specific network for testing them.

**Comment by gut** [comment]
for now, I'll use networks I created on my GCP project outside daisy

**Comment by gut** [comment]
@adjackura Hi. Do you think this should be done and the #438 updated just like you pointed out on https://github.com/GoogleCloudPlatform/compute-image-tools/pull/434#issuecomment-395541756 ?

**Comment by gut** [comment]
@adjackura ping. Do you have a position on this one?

**Comment by adjackura** [comment]
We already have a createnetworks step type, we should probably just add a
createsubnetworks step type also.
