### ISSUE TITLE
[question/daisy] Why no region parameter?

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#445]
I'm implementing ForwardingRule step on daisy as requested on https://github.com/GoogleCloudPlatform/compute-image-tools/pull/437#issuecomment-397135784 but I see that daisy is not ready for using region as a parameter. In order to implement it I thought about:

1) Implicitly define it from zone when needed (basically `region = zone[:-2]`)
2) Add a parameter `-region` to be passed by command line for supplying that information, otherwise a valid error like `no region provided in step or workflow` might occur.

What's your opinion on this?

**Comment by adjackura** [comment]
I like the idea of implying the default region from the default zone, we
may also want a top level Daisy default in the worklfow/flag too as I
believe I made zone optional. Technically you could just be working with
regional resources so demanding you specify zone doesn't make sense.

**Comment by gut** [comment]
Working only with regional resources? I always instantiate a machine so I always needed to define a zone.

I can implement this later, but for now, please check the first approach I implemented on #434 , specifically https://github.com/GoogleCloudPlatform/compute-image-tools/pull/434/commits/c9f1884fdb3270910b389b5e57fbf45b5fc64084#diff-7b1669af81e6327ae6d38b7c32b4003bR57

**Comment by gut** [comment]
well, It's working thanks to #434. I'll soon make use of it again for managing subnetworks on daisy so I guess this task can be closed for now
