### ISSUE TITLE
[instance creation] Support for create VMs in a shared VPC

### ISSUE THREAD

**Issue by lukeFalsina** [GoogleCloudPlatform/compute-image-tools#479]
Hello,

I was wondering whether daisy can support the possibility to create an instance inside of a shared VPC (https://cloud.google.com/vpc/docs/shared-vpc).

The code here:
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy/instance.go
always requires to provide as network interface both a network and a subnetwork.

However, with a shared VPC the network does not belong to the project where the instance is created and thus daisy breaks (or I was not able to make it work anyhow).

I checked the REST APIs for creating an instance in a shared VPC and only the subnetwork argument is provided so this looks like being the right approach to adapt here. For example:
```
  "networkInterfaces": [
    {
      "kind": "compute#networkInterface",
      "subnetwork": "projects/my-other-project-id/regions/europe-west1/subnetworks/my-shared-vpc-name"
    }
```

Thoughts here?

**Comment by adjackura** [comment]
Looks like we add the default network if 'network' is not set, this may not be correct if subnetwork is set. Ill do some testing and make sure we dont populate fields we shouldn't and that our validation matches what the API expects.

**Comment by adjackura** [comment]
Created #480 to hopefully fix this, we don't have any end to end integration tests with shared VPCs so I can't test your exact use case right now, I'll look into adding a test case that would cover this.

**Comment by lukeFalsina** [comment]
Hey @adjackura ,

Thanks for looking at this one. I just tried out downloading the latest version of Daisy based on master and test out with a VM in shared VPC. Instance creations looks like working correctly, however later on in my test case I'm waiting for a signal on the serial output of the VM and the match on the successful string is missed (I can see the string being available in the GCS logs but the operator never getting that back until timeout kicks in).

So it seems like there is a bug somewhere there. The code that I am using for my test is based on this template:
https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/master/custom-images/constants.py#L73

Before testing your change, I was using the release version of Daisy, which according to the tag looks like one year old :/ So a lot has been going on there..
In such version the signal was correctly captured.

**Comment by lukeFalsina** [comment]
Hey @adjackura ,

I take it back. It looks like it was just a flacky execution. I tried my test case again using a VM on a shared VPC and the Daisy workflow was successfully executed and specifically the wait for a signal mechanism worked fine.

**Comment by adjackura** [comment]
Closing as I think your issue is solved. Let me know if that is not the case.
