### ISSUE TITLE
[Daisy] [Question] [RFQ] Create a public file in a bucket

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-tools#481]
I know that daisy can upload files to buckets, e.g, the "Sources" Workflow field. However I can't configure that file permissions, and I would want to configure it as public for my workload.

Do you have any suggestions for this? I consider implementing a different structure for the "Sources" field which the file parameters would be available to configure. I'd also care to not break compatibility with current implementation, so I hope both of them can be accepted. It'd be something like:
```
"Sources": {
 "public_file": {"Name": "./local_file", "PredefinedAcl": "publicRead"},
 "private_file": "./secret_file"
}
```

I'd try to stick with the Storage's APIs paramenter as defined on https://cloud.google.com/storage/docs/json_api/v1/objects/insert

**Comment by adjackura** [comment]
Sources are just meant for daisy scratch resources, we really shouldn't be needing to specify permissions. if you need move GCS files around and set permsions see CopyGCSObjects step:
https://googlecloudplatform.github.io/compute-image-tools/daisy-workflow-config-spec.html#type-copygcsobjects

This can also be used to change permissions in place so you can use the same scratch path for files.

**Comment by gut** [comment]
Didn't know that CopyGCSObjects, that matches what I want. Thanks!
