### ISSUE TITLE
[instance creation] Support for create VMs with internal IP only

### ISSUE THREAD

**Issue by lukeFalsina** [GoogleCloudPlatform/compute-image-tools#506]
Current code here (https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy/instance.go#L203) always enforces an external IP to be assigned to a VM at creation time.

It would be very useful if that would not be always enforced and instead we could also create instances with internal IPs only.

**Comment by adjackura** [comment]
This is just daisy setting the defaults similar to gcloud or the cloud console. If you want to you can specifically set a blank AccessConfigs to create instances without external IP's:

"networkInterfaces": [
  {
    "accessConfigs": []
   }
],
