### ISSUE TITLE
rename package_library dir to 'packages', etc

### ISSUE THREAD

**Issue by skelterjohn** [GoogleCloudPlatform/compute-image-tools#557]
By convention, the directory name matches the package name. Otherwise it's very confusing in the code that imports the package - it's not immediately clear which import corresponds to the identifier.

**Comment by adjackura** [comment]
Having a packages folder at the top level was deemed worse than the naming oddity as there are no packages defined in this directory, just a go library dealing with packages. This code will most likely move in the future to a subdirectory so the naming can be fixed then.

**Comment by skelterjohn** [comment]
In that case, yes I second the idea of moving `packages_dir` to someting like `client/packages`

**Comment by adjackura** [comment]
I bundled this change into #558
