### ISSUE TITLE
[daisy] Cleanup doesn't work?

### ISSUE THREAD

**Issue by sergiik** [GoogleCloudPlatform/compute-image-tools#560]
I'm importing images using steps from this manual https://googlecloudplatform.github.io/compute-image-tools/image-import.html
Images are created as expected but cleanup seems not working or at least not everything is cleaned.
In particular data in bucket ${project}-daisy-bkt automatically created by daisy is not cleaned and the following folders are still present even after import operation successfully finished.

${project}-daisy-bkt/daisy-import-image-20181019-08:41:53-tyr8l/sources
${project}-daisy-bkt/daisy-import-image-20181019-08:41:53-tyr8l/logs

"NoCleanup" is set to 'false' in both workflows. Is it indented behavior and cleanup of those folders should be done manually? 

import_image.wf.json:
...
    "create-image": {
      "CreateImages": [
        {
          "Name": "${image_name}",
          "SourceDisk": "${import_disk_name}",
          "Family": "${family}",
          "Description": "${description}",
          "ExactName": true,
          "NoCleanup": false
        }
      ]
},

import_disk.wf.json:
...
    "setup-disks": {
      "CreateDisks": [
        {
          "Name": "disk-importer",
          "SourceImage": "${import_instance_disk_image}",
          "SizeGb": "${importer_instance_disk_size}",
          "Type": "pd-ssd"
        },
        {
          "Name": "${disk_name}",
          "SizeGb": "10",
          "Type": "pd-ssd",
          "ExactName": true,
          "NoCleanup": false
        }
      ]
},

**Comment by adjackura** [comment]
Right now this is working as intended. Daisy does not cleanup the GCS scratch directory as it is useful for debugging and logging.
