### ISSUE TITLE
Unable to pass boolean variable

### ISSUE THREAD

**Issue by ryanhaining** [GoogleCloudPlatform/compute-image-tools#630]
I'm running a script that runs daisy and I want to conditionally set `NoCleanup`. Attempts have been unsuccessful. In my `create-disk` step

```json
"NoCleanup": "${retain_disk}"
```

I've tried a few things inside `Vars`
```json
"Vars": {
    "retain_disk": false
}
```

Which results in 
```
cannot unmarshal bool into Go value of type struct { *daisy.aVar }
```

and

```json
"retain_disk": "false"
```
which gives me
```
cannot unmarshal string into Go struct field Disk.NoCleanup of type bool
```

I imagine that the latter is closer to what I'd actually want to work since passing from the command line would always pass strings to vars. Is there any way to pass a bool?

**Comment by zoran15** [comment]
NoCleanup is a boolean field. Unfortunately, Daisy currently doesn't support boolean variables. We'll be working on fixing this.

In the mean time, the only workaround I can currently come up with is having two workflow files with different NoCleanup values set directly in the step and calling Daisy with different workflow files. 

Please keep an eye on this issue to get updates on the fix.

**Comment by ryanhaining** [comment]
thanks for confirming. I think for the time being I'll generate the workflow file rather than duplicating everything, there's enough going on in it that I don't want to maintain two copies of it.
