### ISSUE TITLE
gce_export: unclear how -licenses flag should be specified

### ISSUE THREAD

**Issue by functicons** [GoogleCloudPlatform/compute-image-tools#661]
It is unclear how the `-licenses` flag should be specified in [gce_export](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/cli_tools/gce_export/README.md#flags). An example would be helpful.

**Comment by zmarano** [comment]
You should add licenses when creating the images instead of exporting the image. For all intents and purposes- ignore the -licenses flag for export.
