### ISSUE TITLE
Can this binary run on 32-bit VM?

### ISSUE THREAD

**Issue by hanglearning** [GoogleCloudPlatform/compute-image-tools#734]
When I try to run it directly from the terminal, it always shows me 

cannot execute binary file: Exec format error

I then checked online and someone mentions it might be as running a 64-bit executable on a 32-bit machine. My VM is indeed 32-bit.

Is there any solution? Thanks!

**Comment by rofuentes** [comment]
This repository contains the source code for multiple binaries, are you referring to daisy?

**Comment by hanglearning** [comment]
Hi rofuentes, sorry for the confusion! I mean this import_precheck binary. Once I try to run it in my Ubuntu 16.04 it always return: cannot execute binary file: Exec format error.

**Comment by rofuentes** [comment]
Yes, that binary is for 64-bit architectures. Google Compute Engine is starting to support 32-bit arch on Windows VMs, but I do not know the status for Linux. Let me check with my teammates and I will let you know.

**Comment by hanglearning** [comment]
Oh gotcha rofuentes I appreciate it! :D

**Comment by rofuentes** [comment]
After discussing options with my teammate @zmarano, it seems we cannot support 32-bit Ubuntu (or other Linux distribution) on our platform. Is it possible to upgrade your VM to a 64-bit os?

**Comment by hanglearning** [comment]
My system admin is able to make this decision. I will let him know. Thanks for you guys' input! 👍
