### ISSUE TITLE
Import gcloud compute.disks.resize error

### ISSUE THREAD

**Issue by raulramirezj** [GoogleCloudPlatform/compute-image-tools#786]
Hello Im using gcloud SDK and was able to upload VM, however when trying to import a 58GB file I got an error:  Failed to resize temp-translation-disk-2j5r3 to 108GB 

Any help will be highly appreciated, thanks.

This is the full log: 

starting build "707113af-36ed-467c-9bfb-5779f7f60d03"

FETCHSOURCE
BUILD
Pulling image: gcr.io/compute-image-tools/daisy:release
release: Pulling from compute-image-tools/daisy
8166f5a2b2e9: Pulling fs layer
0ac2efe37c3b: Pulling fs layer
77b74e41257d: Pulling fs layer
77b74e41257d: Verifying Checksum
77b74e41257d: Download complete
8166f5a2b2e9: Verifying Checksum
8166f5a2b2e9: Download complete
8166f5a2b2e9: Pull complete
0ac2efe37c3b: Verifying Checksum
0ac2efe37c3b: Download complete
0ac2efe37c3b: Pull complete
77b74e41257d: Pull complete
Digest: sha256:015bbeeb4ff88e3cc858a1146b168fc5e14cff19261e07cc3aacd6e394f83e06
Status: Downloaded newer image for gcr.io/compute-image-tools/daisy:release
[Daisy] Running workflow "import-and-translate" (id=2j5r3)
[import-and-translate]: 2019-05-10T19:47:04Z Validating workflow
[import-and-translate]: 2019-05-10T19:47:04Z Validating step "import"
[import-and-translate.import]: 2019-05-10T19:47:04Z Validating step "setup-disks"
[import-and-translate.import]: 2019-05-10T19:47:04Z Validating step "import-virtual-disk"
[import-and-translate.import]: 2019-05-10T19:47:05Z Validating step "wait-for-signal"
[import-and-translate]: 2019-05-10T19:47:05Z Validating step "translate"
[import-and-translate.translate]: 2019-05-10T19:47:05Z Validating step "setup-disks"
[import-and-translate.translate]: 2019-05-10T19:47:05Z Validating step "translate-disk"
[import-and-translate.translate.translate-disk]: 2019-05-10T19:47:05Z Validating step "translate-disk-inst"
[import-and-translate.translate.translate-disk]: 2019-05-10T19:47:05Z Validating step "wait-for-translator"
[import-and-translate.translate.translate-disk]: 2019-05-10T19:47:05Z Validating step "delete-instance"
[import-and-translate.translate]: 2019-05-10T19:47:05Z Validating step "create-image"
[import-and-translate]: 2019-05-10T19:47:05Z Validating step "cleanup"
[import-and-translate]: 2019-05-10T19:47:05Z Validation Complete
[import-and-translate]: 2019-05-10T19:47:05Z Workflow Project: strange-terra-239901
[import-and-translate]: 2019-05-10T19:47:05Z Workflow Zone: us-west1-a
[import-and-translate]: 2019-05-10T19:47:05Z Workflow GCSPath: gs://strange-terra-239901-daisy-bkt/
[import-and-translate]: 2019-05-10T19:47:05Z Daisy scratch path: https://console.cloud.google.com/storage/browser/strange-terra-239901-daisy-bkt/daisy-import-and-translate-20190510-19:47:04-2j5r3
[import-and-translate]: 2019-05-10T19:47:05Z Uploading sources
[import-and-translate]: 2019-05-10T19:47:07Z Running workflow
[import-and-translate]: 2019-05-10T19:47:07Z Running step "import" (IncludeWorkflow)
[import-and-translate.import]: 2019-05-10T19:47:07Z Running step "setup-disks" (CreateDisks)
[import-and-translate.import.setup-disks]: 2019-05-10T19:47:07Z CreateDisks: Creating disk "disk-importer-import-and-translate-import-2j5r3".
[import-and-translate.import.setup-disks]: 2019-05-10T19:47:07Z CreateDisks: Creating disk "temp-translation-disk-2j5r3".
[import-and-translate.import]: 2019-05-10T19:47:41Z Step "setup-disks" (CreateDisks) successfully finished.
[import-and-translate.import]: 2019-05-10T19:47:41Z Running step "import-virtual-disk" (CreateInstances)
[import-and-translate.import.import-virtual-disk]: 2019-05-10T19:47:41Z CreateInstances: Creating instance "inst-importer-import-and-translate-import-2j5r3".
[import-and-translate.import]: 2019-05-10T19:47:54Z Step "import-virtual-disk" (CreateInstances) successfully finished.
[import-and-translate.import]: 2019-05-10T19:47:54Z Running step "wait-for-signal" (WaitForInstancesSignal)
[import-and-translate.import.import-virtual-disk]: 2019-05-10T19:47:54Z CreateInstances: Streaming instance "inst-importer-import-and-translate-import-2j5r3" serial port 1 output to https://storage.cloud.google.com/strange-terra-239901-daisy-bkt/daisy-import-and-translate-20190510-19:47:04-2j5r3/logs/inst-importer-import-and-translate-import-2j5r3-serial-port1.log
[import-and-translate.import.wait-for-signal]: 2019-05-10T19:47:54Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-2j5r3": watching serial port 1, SuccessMatch: "ImportSuccess:", FailureMatch: "ImportFailed:", StatusMatch: "Import:".
[import-and-translate.import.wait-for-signal]: 2019-05-10T19:48:14Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-2j5r3": StatusMatch found: "Import: Importing strange-terra-239901-daisy-bkt/tmpimage/6e4c2086-78cb-436c-b6be-4e182ad69df0-main.vmdk of size 108GB to temp-translation-disk-2j5r3 in projects/88626496651/zones/us-west1-a.'"
[import-and-translate.import.wait-for-signal]: 2019-05-10T19:48:14Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-2j5r3": StatusMatch found: "Import: Importing strange-terra-239901-daisy-bkt/tmpimage/6e4c2086-78cb-436c-b6be-4e182ad69df0-main.vmdk of size 108GB to temp-translation-disk-2j5r3 in projects/88626496651/zones/us-west1-a."
[import-and-translate]: 2019-05-10T19:48:24Z Error running workflow: step "import" run error: step "wait-for-signal" run error: WaitForInstancesSignal FailureMatch found for "inst-importer-import-and-translate-import-2j5r3": "ImportFailed: Failed to resize temp-translation-disk-2j5r3 to 108GB in projects/88626496651/zones/us-west1-a, error: ERROR: (gcloud.compute.disks.resize) Could not fetch resource:"
[import-and-translate]: 2019-05-10T19:48:24Z Workflow "import-and-translate" cleaning up (this may take up to 2 minutes).

[Daisy] Errors in one or more workflows:
  import-and-translate: step "import" run error: step "wait-for-signal" run error: WaitForInstancesSignal FailureMatch found for "inst-importer-import-and-translate-import-2j5r3": "ImportFailed: Failed to resize temp-translation-disk-2j5r3 to 108GB in projects/88626496651/zones/us-west1-a, error: ERROR: (gcloud.compute.disks.resize) Could not fetch resource:"
ERROR
ERROR: build step 0 "gcr.io/compute-image-tools/daisy:release" failed: exit status 1

**Comment by zoran15** [comment]
Can you please check you're not exceeding your Persistent Disk SSD quota in us-west1-a zone?

You can also try importing in a different zone in case the quotas are actually the issue.

**Comment by raulramirezj** [comment]
Thanks Zoran, Actually I deleted a few images that were in the "temp" folder under the bucket section and retried after that.

It came with an error again in this last attempt, however is a different error:


starting build "d556a86a-3dfc-4663-9c9a-b8c6d01cef46"

FETCHSOURCE
BUILD
Pulling image: gcr.io/compute-image-tools/daisy:release
release: Pulling from compute-image-tools/daisy
8166f5a2b2e9: Pulling fs layer
0ac2efe37c3b: Pulling fs layer
77b74e41257d: Pulling fs layer
77b74e41257d: Verifying Checksum
77b74e41257d: Download complete
8166f5a2b2e9: Verifying Checksum
8166f5a2b2e9: Download complete
8166f5a2b2e9: Pull complete
0ac2efe37c3b: Verifying Checksum
0ac2efe37c3b: Download complete
0ac2efe37c3b: Pull complete
77b74e41257d: Pull complete
Digest: sha256:015bbeeb4ff88e3cc858a1146b168fc5e14cff19261e07cc3aacd6e394f83e06
Status: Downloaded newer image for gcr.io/compute-image-tools/daisy:release
[Daisy] Running workflow "import-and-translate" (id=w9ws1)
[import-and-translate]: 2019-05-10T22:26:26Z Validating workflow
[import-and-translate]: 2019-05-10T22:26:26Z Validating step "import"
[import-and-translate.import]: 2019-05-10T22:26:26Z Validating step "setup-disks"
[import-and-translate.import]: 2019-05-10T22:26:26Z Validating step "import-virtual-disk"
[import-and-translate.import]: 2019-05-10T22:26:27Z Validating step "wait-for-signal"
[import-and-translate]: 2019-05-10T22:26:27Z Validating step "translate"
[import-and-translate.translate]: 2019-05-10T22:26:27Z Validating step "setup-disks"
[import-and-translate.translate]: 2019-05-10T22:26:27Z Validating step "translate-disk"
[import-and-translate.translate.translate-disk]: 2019-05-10T22:26:27Z Validating step "translate-disk-inst"
[import-and-translate.translate.translate-disk]: 2019-05-10T22:26:27Z Validating step "wait-for-translator"
[import-and-translate.translate.translate-disk]: 2019-05-10T22:26:27Z Validating step "delete-instance"
[import-and-translate.translate]: 2019-05-10T22:26:27Z Validating step "create-image"
[import-and-translate]: 2019-05-10T22:26:27Z Validating step "cleanup"
[import-and-translate]: 2019-05-10T22:26:27Z Validation Complete
[import-and-translate]: 2019-05-10T22:26:27Z Workflow Project: strange-terra-239901
[import-and-translate]: 2019-05-10T22:26:27Z Workflow Zone: us-west1-a
[import-and-translate]: 2019-05-10T22:26:27Z Workflow GCSPath: gs://strange-terra-239901-daisy-bkt/
[import-and-translate]: 2019-05-10T22:26:27Z Daisy scratch path: https://console.cloud.google.com/storage/browser/strange-terra-239901-daisy-bkt/daisy-import-and-translate-20190510-22:26:26-w9ws1
[import-and-translate]: 2019-05-10T22:26:27Z Uploading sources
[import-and-translate]: 2019-05-10T22:26:29Z Running workflow
[import-and-translate]: 2019-05-10T22:26:29Z Running step "import" (IncludeWorkflow)
[import-and-translate.import]: 2019-05-10T22:26:29Z Running step "setup-disks" (CreateDisks)
[import-and-translate.import.setup-disks]: 2019-05-10T22:26:29Z CreateDisks: Creating disk "disk-importer-import-and-translate-import-w9ws1".
[import-and-translate.import.setup-disks]: 2019-05-10T22:26:29Z CreateDisks: Creating disk "temp-translation-disk-w9ws1".
[import-and-translate.import]: 2019-05-10T22:26:53Z Step "setup-disks" (CreateDisks) successfully finished.
[import-and-translate.import]: 2019-05-10T22:26:53Z Running step "import-virtual-disk" (CreateInstances)
[import-and-translate.import.import-virtual-disk]: 2019-05-10T22:26:53Z CreateInstances: Creating instance "inst-importer-import-and-translate-import-w9ws1".
[import-and-translate.import]: 2019-05-10T22:27:06Z Step "import-virtual-disk" (CreateInstances) successfully finished.
[import-and-translate.import]: 2019-05-10T22:27:06Z Running step "wait-for-signal" (WaitForInstancesSignal)
[import-and-translate.import.import-virtual-disk]: 2019-05-10T22:27:06Z CreateInstances: Streaming instance "inst-importer-import-and-translate-import-w9ws1" serial port 1 output to https://storage.cloud.google.com/strange-terra-239901-daisy-bkt/daisy-import-and-translate-20190510-22:26:26-w9ws1/logs/inst-importer-import-and-translate-import-w9ws1-serial-port1.log
[import-and-translate.import.wait-for-signal]: 2019-05-10T22:27:06Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-w9ws1": watching serial port 1, SuccessMatch: "ImportSuccess:", FailureMatch: "ImportFailed:", StatusMatch: "Import:".
[import-and-translate.import.wait-for-signal]: 2019-05-10T22:27:17Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-w9ws1": StatusMatch found: "Import: Importing strange-terra-239901-daisy-bkt/tmpimage/b9470302-9a23-40af-a4bf-02914c2bdcba-main.vmdk of size 108GB to temp-translation-disk-w9ws1 in projects/88626496651/zones/us-west1-a.'"
[import-and-translate.import.wait-for-signal]: 2019-05-10T22:27:17Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-w9ws1": StatusMatch found: "Import: Importing strange-terra-239901-daisy-bkt/tmpimage/b9470302-9a23-40af-a4bf-02914c2bdcba-main.vmdk of size 108GB to temp-translation-disk-w9ws1 in projects/88626496651/zones/us-west1-a."
[import-and-translate.import.wait-for-signal]: 2019-05-10T22:58:16Z WaitForInstancesSignal: Instance "inst-importer-import-and-translate-import-w9ws1": SuccessMatch found "ImportSuccess: Finished import.'"
[import-and-translate.import]: 2019-05-10T22:58:16Z Step "wait-for-signal" (WaitForInstancesSignal) successfully finished.
[import-and-translate]: 2019-05-10T22:58:16Z Step "import" (IncludeWorkflow) successfully finished.
[import-and-translate]: 2019-05-10T22:58:16Z Running step "translate" (IncludeWorkflow)
[import-and-translate.translate]: 2019-05-10T22:58:16Z Running step "setup-disks" (CreateDisks)
[import-and-translate.translate.setup-disks]: 2019-05-10T22:58:16Z CreateDisks: Creating disk "disk-translator-import-and-translate-translate-w9ws1".
[import-and-translate.translate]: 2019-05-10T22:58:19Z Step "setup-disks" (CreateDisks) successfully finished.
[import-and-translate.translate]: 2019-05-10T22:58:19Z Running step "translate-disk" (IncludeWorkflow)
[import-and-translate.translate.translate-disk]: 2019-05-10T22:58:19Z Running step "translate-disk-inst" (CreateInstances)
[import-and-translate.translate.translate-disk.translate-disk-inst]: 2019-05-10T22:58:19Z CreateInstances: Creating instance "inst-translator-import-and-translate-translate-translate-w9ws1".
[import-and-translate.translate.translate-disk]: 2019-05-10T22:58:31Z Step "translate-disk-inst" (CreateInstances) successfully finished.
[import-and-translate.translate.translate-disk]: 2019-05-10T22:58:31Z Running step "wait-for-translator" (WaitForInstancesSignal)
[import-and-translate.translate.translate-disk.translate-disk-inst]: 2019-05-10T22:58:31Z CreateInstances: Streaming instance "inst-translator-import-and-translate-translate-translate-w9ws1" serial port 1 output to https://storage.cloud.google.com/strange-terra-239901-daisy-bkt/daisy-import-and-translate-20190510-22:26:26-w9ws1/logs/inst-translator-import-and-translate-translate-translate-w9ws1-serial-port1.log
[import-and-translate.translate.translate-disk.wait-for-translator]: 2019-05-10T22:58:31Z WaitForInstancesSignal: Instance "inst-translator-import-and-translate-translate-translate-w9ws1": watching serial port 1, SuccessMatch: "TranslateSuccess:", FailureMatch: "TranslateFailed:".
[import-and-translate.translate.translate-disk.translate-disk-inst]: 2019-05-10T23:25:50Z CreateInstances: Instance "inst-translator-import-and-translate-translate-translate-w9ws1": error saving log to GCS: Post https://www.googleapis.com/upload/storage/v1/b/strange-terra-239901-daisy-bkt/o?alt=json&prettyPrint=false&projection=full&uploadType=multipart: oauth2/google: incomplete token received from metadata
2019/05/10 23:25:53 logging client: rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Flogging.write: net/http: timeout awaiting response headers
2019/05/10 23:26:10 logging client: rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Flogging.write: net/http: timeout awaiting response headers
2019/05/10 23:26:18 logging client: rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Flogging.write: net/http: timeout awaiting response headers
2019/05/10 23:26:42 logging client: rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Flogging.write: net/http: timeout awaiting response headers
[import-and-translate.import.import-virtual-disk]: 2019-05-10T23:26:07Z CreateInstances: Instance "inst-importer-import-and-translate-import-w9ws1": error getting serial port: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-importer-import-and-translate-import-w9ws1/serialPort?alt=json&port=1&prettyPrint=false&start=115102: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers
[import-and-translate.translate.translate-disk.translate-disk-inst]: 2019-05-10T23:26:15Z CreateInstances: Instance "inst-translator-import-and-translate-translate-translate-w9ws1": error getting serial port: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-translator-import-and-translate-translate-translate-w9ws1/serialPort?alt=json&port=1&prettyPrint=false&start=816152: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers
[import-and-translate]: 2019-05-10T23:26:39Z Error running workflow: step "translate" run error: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal: instance "inst-translator-import-and-translate-translate-translate-w9ws1": error getting serial port: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-translator-import-and-translate-translate-translate-w9ws1/serialPort?alt=json&port=1&prettyPrint=false&start=815811: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers, error getting InstanceStatus: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-translator-import-and-translate-translate-translate-w9ws1?alt=json&prettyPrint=false: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers
[import-and-translate]: 2019-05-10T23:28:07Z Workflow "import-and-translate" cleaning up (this may take up to 2 minutes).

[Daisy] Errors in one or more workflows:
  import-and-translate: step "translate" run error: step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal: instance "inst-translator-import-and-translate-translate-translate-w9ws1": error getting serial port: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-translator-import-and-translate-translate-translate-w9ws1/serialPort?alt=json&port=1&prettyPrint=false&start=815811: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers, error getting InstanceStatus: Get https://www.googleapis.com/compute/v1/projects/strange-terra-239901/zones/us-west1-a/instances/inst-translator-import-and-translate-translate-translate-w9ws1?alt=json&prettyPrint=false: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write: net/http: timeout awaiting response headers
ERROR
ERROR: build step 0 "gcr.io/compute-image-tools/daisy:release" failed: exit status 1

**Comment by raulramirezj** [comment]
I found more information regarding the 1st error and I believe you are correct. 

Under Operations I found the history and there I found the  "Quota Exceeded" listed along the 'resize disk" operation. These are the details when I clicked it:


 operation-1557518123107-5888df275868c-f6b51406-35c5e9e0
Error
QUOTA_EXCEEDED: Quota 'SSD_TOTAL_GB' exceeded. Limit: 100.0 in region us-west1. 
Operation type
resizeDisk
Target type
Disks
Target
temp-translation-disk-xswbj
Target ID
7744660102345943058
Progress
100%
User

So now I changed to region west 2a. I will let you know the result.

Thank you.

**Comment by zoran15** [comment]
You can also request a quota increase so you don't have to switch zones just because you've exhausted current quota in a zone.

Please update the status once you tried a different zone and whether the second error reported has gone away (http timeouts/failure to get auth token)

**Comment by raulramirezj** [comment]
@zoran15.

Thank you. I was able to upload the file once I changed to zone us-west2. FIXED!
