### ISSUE TITLE
Error uploading VM image with gcloud compute images import 

### ISSUE THREAD

**Issue by raulramirezj** [GoogleCloudPlatform/compute-image-tools#789]
Hello, I was able to upload a file 2 days ago after I changed zone to us-west2-a. But today I got this error message when running the same procedure:

[Daisy] Errors in one or more workflows:
  import-and-translate: step "import" validation error: step "import-virtual-disk" validation error: ResourceDoesNotExist: projects/strange-terra-239901/global/networks/default does not exist
[import-and-translate]: 2019-05-13T20:42:48Z Error validating workflow: step "import" validation error: step "import-virtual-disk" validation error: ResourceDoesNotExist: projects/strange-terra-239901/global/networks/default does not exist
ERROR

I opened the tmpimage buket and the file shows there:f4c92a07-fca2-4cb8-989c-9936f79c4e99-postgres2.vmdk

Thanks in advance.

**Comment by zoran15** [comment]
It appears there's no default network present in the project anymore. You'll have to use --network (and potentially --subnet) flags to specify a network to be used during import process.

**Comment by raulramirezj** [comment]
Thank you @zoran15. Is there a way for me to try to build the image from the Temp folder so I dont have to upload the whole 67GB again?

**Comment by zoran15** [comment]
--source-file can be a path to a file in GCS, e.g. --source-file=gs:/your-bucket/your-file

Please use `gcloud compute images import --help` or the following pages for more help with using image import functionality:
https://cloud.google.com/sdk/gcloud/reference/compute/images/import
https://cloud.google.com/compute/docs/images/importing-virtual-disks

This GitHub repo is for Daisy and it's derivatives which are used internally in image import but they are open source. 

More info on Google Cloud Support: https://support.google.com/cloud/answer/6282346

Feel free to create bug reports for any bugs in Daisy or it's derivatives here.
