### ISSUE TITLE
Export log file from build/import VM

### ISSUE THREAD

**Issue by rofuentes** [GoogleCloudPlatform/compute-image-tools#866]
Add functionality to define 1 - many log files that will be copied to GCS bucket before failing or completing the workflow.

Windows tools such as Sysprep and DISM log to separate log files, and retrieving logs requires modifying the workflow to save the build/import disk. It would be more convenient to save logs containing the errors so that they can be investigated.

**Comment by zoran15** [comment]
How should log files to be copied to GCS be specified? 

Are file names fixed or they can have a variable part? What about paths?

Will the number of log files be variable or fixed (e.g. will logging of a single tool be spread of multiple files)?

**Comment by dntczdx** [comment]
It would be helpful to have a concrete example.

**Comment by rofuentes** [comment]
We run Sysprep at the end of an image build, that logs to [C:\Windows32\Sysprep\Panther.](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep-process-overview#sysprep-log-files) If there is an error during Sysprep, this is documented in this txt log file. Nothing is sent to the serial console or to another centralized logging facility. The only way to determine what is happening is to RDP into the instance while it build and view the log. This requires you to watch the build for ~3 hours and log in at the appropriate time.

I would like to be able to specify a log file location (absolute path) and have that file sent to a GCS bucket of my choice. This happens somewhat frequently, CBS is another example - Windows Update, uses at lease [2 log files in different filepaths](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs) to record errors.

I can simply modify our PowerShell files to copy the files using gsutil, but I thought adding this functionality would be worthwhile.

Regarding the other questions:
Log files are specified by absolute paths
File names are fixed, no variables
The number of log files is variable
