### ISSUE TITLE
Workflows failing because of transport-level errors

### ISSUE THREAD

**Issue by rkolchmeyer** [GoogleCloudPlatform/compute-image-tools#918]
We've recently started observing a significantly higher rate of Daisy workflows failing due to transport-level errors (starting roughly around 9/10). Here are some example errors:

\<workflow>: step "run" validation error: cannot create instance, bad machineType lookup: "n1-standard-1", error: error listing machine types for project "\<project>": Get https://www.googleapis.com/compute/v1/projects/<project\>/zones/us-west1-b/machineTypes?alt=json&pageToken=&prettyPrint=false: unexpected EOF

\<workflow>: step "run" run error: Post https://www.googleapis.com/compute/v1/projects/<project\>/zones/us-west1-b/instances?alt=json&prettyPrint=false: unexpected EOF

\<workflow>: step "run" run error: Post https://www.googleapis.com/compute/v1/projects/<project\>/zones/us-west1-b/instances?alt=json&prettyPrint=false: read tcp 192.168.10.2:59590->74.125.135.95:443: read: connection reset by peer

\<workflow>: step "wait-disk-formatter" run error: APIError: Get https://compute.googleapis.com/compute/v1/projects/<project\>/zones/us-west1-a/instances/<instance\>?alt=json&prettyPrint=false: read tcp 192.168.10.2:49496->172.217.212.95:443: read: connection reset by peer

\<workflow>: step "setup" validation error: cannot create disk "boot-disk": can't use image "projects/<project>/global/images/<image\>": error listing images for project "\<project>": Get https://www.googleapis.com/compute/v1/projects/<project\>/global/images?alt=json&pageToken=&prettyPrint=false: unexpected EOF

We haven't changed our workflows in any way. Looking at https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy/compute/compute.go#L187, it seems to me that these types of errors aren't retried. Would it make sense to check for these types of errors and retry the failing HTTP requests?

**Comment by dntczdx** [comment]
#919 has been merged
